---
- name: Create AWS key pair
  amazon.aws.ec2_key:
    name: "{{ key_name }}"
    key_material: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    region: "{{ aws_region }}"
    state: present
    tags: "{{ resource_tags }}"
  tags: [keypair, aws]