name: Deploy Application

on:
  push:
    branches:
      - 'feat_*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag to deploy'
        required: true
        default: 'latest'
        type: string

env:
  DOCKER_COMPOSE_FILE: docker-compose.yaml
  DEPLOY_DIR: /opt/fortstack

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set deployment variables
        id: vars
        run: |
          echo "tag=${{ github.event.inputs.tag || 'latest' }}" >> $GITHUB_OUTPUT
          echo "Deploying with tag: ${{ github.event.inputs.tag || 'latest' }}"

      - name: Update Docker Compose for deployment
        run: |
          cd ${{ env.DEPLOY_DIR }}
          
          cp docker-compose.yml docker-compose.yml.backup
          
          sed -i "s|image: 645537741587.dkr.ecr.us-west-1.amazonaws.com/omnia/backend|image: 645537741587.dkr.ecr.us-west-1.amazonaws.com/omnia/backend:${{ steps.vars.outputs.tag }}|g" docker-compose.yml
          sed -i "s|image: 645537741587.dkr.ecr.us-west-1.amazonaws.com/omnia/frontend|image: 645537741587.dkr.ecr.us-west-1.amazonaws.com/omnia/frontend:${{ steps.vars.outputs.tag }}|g" docker-compose.yml
                    
          echo "Updated docker-compose.yml with tag: ${{ steps.vars.outputs.tag }}"

     
      - name: Stop existing services
        run: |
          cd ${{ env.DEPLOY_DIR }}
          docker compose down || true

      - name: Deploy services
        run: |
          cd ${{ env.DEPLOY_DIR }}
          docker compose up -d